### ISSUE TITLE
Suggestion: Make DiscordClient Requirement Optional

### ISSUE THREAD

**Issue by TheMulti0** [Yucked/Victoria#24]
Some people don't actually need to create DiscordClient in order to use the Lavalink REST API only - just for searching tracks, not for connecting to a voice channel.

I say, extract an interface that LavaNode will implement - `ISearchable` which will have the methods: `GetTracksAsync`, `SearchFromYouTube`, `SearchFromSoundcloud`. And Lavalink will have the following method: `ISearchable GetSearchableNode(Configuration config = default)`, which will return an implementation with only the 3 methods above that are only used for search (Lavalink REST API)

**Comment by Yucked** [comment]
That sounds like a good idea. Although GetSearchableNode doesn't make much sense or making an interface. I'd look into a way to separate those methods to give more flexibility.

**Comment by TheMulti0** [comment]
Perhaps a better idea is to have a base class `LavalinkNode` which will have the most basic stuff that have nothing to do with Discord and Lavalink REST API (probably `InitializeAsync(Configuration config = default)` and so).

Then have a class called `SearchableNode` or so - which extends `LavalinkNodeBase` but offers the search method.
Maybe create a few more separations you can think of, but the object that derrives all of the methods and members will be called `LavalinkNode`.
Then Idk.. we can find a way to get each one of those seperately

**Comment by Yucked** [comment]
I can design it like discord.net - LavaSocket, LavaRest, LavaPlayer, SocketManager(?) 

Edit: Wrote that in a hurry.

LavaSocket will act as a node since LavaNode basically handles the socket and rest connection but this time it will only handle socket related stuff.

LavaRest will separatel Rest stuff from LavaNode such as GetTracksAsync and ConfigureResumeAsync.

LavaPlayer will stay the same but almost all methods will be virtual so if user wants to have their own implementation of certain method they can inherit from LavaPlayer. Although I've no idea how I'm going to make it work.

SocketManager will manage all the LavaSockets. Adding/Removing/Moving/etc.

**Comment by TheMulti0** [comment]
That is great!

2 more suggestions:
a. Rename `SocketManager` to `LavaSocketManager`.
b. Have a base class called `LavaBase`, which will have the most basic method - `Initialize` (with config)

**Comment by Yucked** [comment]
I'm looking into renaming the current SocketManage(SocketPool), just want something that isn't super long in terms of naming. And, base class wouldn't make sense at all. This is [LavaRest](https://github.com/Yucked/Victoria/blob/v4/LavaRest.cs) and [LavaSocket](https://github.com/Yucked/Victoria/blob/v4/LavaSocket.cs), they don't have anything in common.

**Comment by TheMulti0** [comment]
Okay then, Very well!
About the base class, I agree but you then may not even want empty interface, or some way to link them, so you can store all of the nodes in one collection.

The hardest thing is figuring out how would one be able to create a node? Perhaps a simple constructor with Configuration as a parameter, since you probably wont be able to add all of the different nodes to one collection (only if you want to have 3 separate collections for each different LavaNode)

**Comment by Yucked** [comment]
I've updated the project structure again. Since there is `DiscordShardedClient` and `DiscordSocketClient` I've split the project into the same way; `BaseLavaClient` - `LavaShardClient` which manages `DiscordShardedClient` and `LavaSocketClient` which manages `DiscordSocketClient`. They both share the same methods besides the disconnect event and all of that implementation is in `LavaBaseClient` which users can also use if they want to make their own client for whatever reason. `LavaRestClient` will stay a separate entity.

**Comment by Yucked** [comment]
Release notes: https://github.com/Yucked/Victoria/wiki/%F0%9F%93%91RELEASE-NOTES

Closing this issue now.

**Comment by TheMulti0** [comment]
Cool! I like how half of the additions are based on my issues xD
