### ISSUE TITLE
Suggestion: Use Newtonsoft.Json (JSON.NET) instead of Microsoft's default serializers

### ISSUE THREAD

**Issue by TheMulti0** [Yucked/Victoria#25]
Newtonsoft.Json is much faster and more powerful than .NET's JSON serializers.
https://www.newtonsoft.com/json/help/html/JsonNetVsDotNetSerializers.htm

**Comment by Yucked** [comment]
Hey, what I was using before was not Microsoft's default serializer but something that is in testing and will be matching Json.NET performance and also replace Json.NET in Asp.NET application:
https://github.com/dotnet/corefxlab/tree/master/src/System.Text.JsonLab.Serialization

Although, for time being I've switched to Json.NET since I need a working prototype but when JsonLab.Serialization is out, I'll be switching to that since the whole project uses C# 8 & Net Core 3.0.

**Comment by TheMulti0** [comment]
I did noticed that you're using C# 8 + .NET Core 3.0, which is great!
However I did not find an online documentation of `JsonLab.Serialization`, so didn't understand the benefits of it yet.

**Comment by Yucked** [comment]
It's just going off of https://github.com/dotnet/corefx/issues/34372

Edit:
Closing this issue now since JSON.NET is being used.
